"use client";
import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import ModalPopup from "@/components/modal/ModalPopup";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nazara",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const router = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        {router === "/payment" ? (
          children
        ) : (
          <>
            <Navbar />
            {children}
            {/* <ModalPopup /> */}
            <Footer />
          </>
        )}
      </body>
    </html>
  );
}
